image: Visual Studio 2017

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '**/*.md'

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: .\Bin\net35
    name: UnityFx.Async-net35
  - path: .\Bin\net46
    name: UnityFx.Async-net46

deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      secure: aTd8m7PLWUlE3iacD7bx9oWPW/CK0+BTE7/nhgB2EXk8iZ3FJ/TJX5kKLIYP76nN
    force_update: false
    on:
      branch: master
