image: Visual Studio 2017

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '**/*.md'

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: .\Build\Bin
    name: UnityFx.Async
