image: Visual Studio 2017

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '**/*.md'

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: .\Build\Bin\net35
    name: UnityFx.Async-net35
  - path: .\Build\Bin\net46
    name: UnityFx.Async-net46

deploy:
 - provider: GitHub
   auth_token:
   secure: HcMqPRgwKBeu9drMO5V8Bbeb4Jn8jCdE8iJz7JiKDnuXbNPLrhRbrzWhavocDhgd
   force_update: false
   on:
    branch: master