image: Visual Studio 2017

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '**/*.md'

build_script:
  - ps: .\build.ps1

test: off

artifacts:
  - path: .\Build\Bin\net35
    name: UnityFx.Async-net35
  - path: .\Build\Bin\net46
    name: UnityFx.Async-net46

deploy:
 - provider: GitHub
   auth_token:
    secure: KdcuA480q9C7+waWIMcGNs17WORwZnlN0Yx9h/0NatT/26XnhKrWYXO3/KCbea1bPxLvzV2ym7PgeYn8PFpQ7zRhf47czcgSEMk6jW27oik=
   force_update: false
   on:
    branch: master