image: Visual Studio 2017

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '**/*.md'

build_script:
  - ps: .\build.ps1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

test: off

artifacts:
  - path: .\Build\Bin\net35
    name: UnityFx.Async-net35
  - path: .\Build\Bin\net46
    name: UnityFx.Async-net46

deploy:
  - provider: GitHub
    auth_token:
      secure: aTd8m7PLWUlE3iacD7bx9oWPW/CK0+BTE7/nhgB2EXk8iZ3FJ/TJX5kKLIYP76nN
    force_update: false
    on:
      branch: master
